### PR TITLE
[RFC] Added CI Testing 

### PR DESCRIPTION
**Pull request by souravsingh**
Added Travis CI testing

### CODE REVIEW

**Comment by jaidevd** [comment]
@souravsingh Thanks for this. In order to test this, I need push access to your fork of pytftb. Let me know when you've granted it.

**Comment by souravsingh** [comment]
@jaidevd I have granted you access to my fork of pytftb

**Comment by jaidevd** [comment]
@souravsingh Thanks, but there seem to be some problem with the builds. Fix them and this will be ready for merging.

**Comment by jaidevd** [comment]
@souravsingh You working on this or shall I close it?

**Comment by souravsingh** [comment]
@jaidevd I am trying to work on the issue

**Comment by jaidevd** [comment]
@souravsingh What's the update on this?

**Comment by jaidevd** [comment]
@souravsingh Never mind.

**Comment by souravsingh** [comment]
@jaidevd Just curious, How were you able to fix the Assertion errors? I wasn't able to fully figure it out.

**Comment by jaidevd** [comment]
Check this https://github.com/scikit-signal/pytftb/pull/83

**Pull request merged**
